### PR TITLE
Style search page

### PR DESCRIPTION
**Pull request by hunterrudnet**
Screenshot 2023-04-03 at 9 37 26 PM

### CODE REVIEW

**Comment by hunterrudnet** [comment]
Screenshot 2023-04-03 at 9 38 05 PM

**Comment by hunterrudnet** [comment]
Also added a cool loading animation when searching

**Comment by hunterrudnet** [comment]
I also added query param for search

**Comment by hunterrudnet** [comment]
Screenshot 2023-04-03 at 10 13 01 PM

**Review by jmac522 — APPROVED** [review]
Nice, looks great

**Pull request merged**
